<html>
<head>
  <title>Cooperative Children's Center - Friday Flyer</title>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width. initial-scale=1">
  <meta name="author" content="Jacklyn Wurtz and Jayme Hewitt">
  <meta name="description" content="This project was a collaboration between Jacklyn Wurtz and Jayme Hewitt. We spent a week working individually/together under various life/time pressures to get this email newsletter shipped. We both intend to continue improving this code as time permits.">
  <style type="text/css"></style>
</head>